############################################################################################################
#                     toml 项目配置文件:
# ref:
#
############################################################################################################

############################################################################################################
# service meta info
############################################################################################################

[meta]
    name = "com.better-go.demo.gateway"
    version = "0.1.0"

############################################################################################################
# require middleware settings
############################################################################################################

# http group:
[HTTP]
    [HTTP.Demo]  # demo
        AppKey = "92f0f39efe6c5a600b1xxxx"
        AppSecret = "748d6b8277a5398790cexxxx"

# db:
[db]
    [db.Demo]  # 区分下划线 和 驼峰命名:
        addr = "172.22.34.1:3306"
        active = 20
        idle = 10
        idleTimeout ="4h"  # 注意自动转换:
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "1s"
    [db.Demo2]
        addr = "172.22.34.2:3306"
        active = 20
        idle = 10
        idleTimeout ="4h"
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "1s"

# cache:
[cache]
    [cache.Demo]
        addr = "1127.0.0.1"



############################################################################################################
# biz settings
############################################################################################################

[biz]
    [biz.Demo]
        app1 = 1
