# This is a basic workflow to help you get started with Actions
#
# ref: 
#   - https://github.com/BobAnkh/add-contributors/blob/master/.github/workflows/contributors.yml
#

name: Add contributors
on:
  #schedule:
  #  - cron:  '20 20 * * *'
  push:
    branches:
      - master

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        CONTRIBUTOR: '## Contributors:'   # TODO X: reset here!
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/readme.md'   # TODO X: check here!
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
